### ISSUE TITLE
Olivetti-mode

### ISSUE THREAD

**Issue by Faiyaz-Nylyx** [protesilaos/standard-themes#2]
Standard-dark-tinted theme shows two gray bars in Olivetti-mode. I don’t know that much eMacs, so can’t provide more information.

**Comment by protesilaos** [comment]
> From: Faiyaz-Nylyx ***@***.***>
> Date: Fri, 27 Dec 2024 03:30:21 -0800
>
> Standard-dark-tinted theme shows to gray bars in Olivetti-mode. I
> don’t know that much eMacs, so can’t provide more information.

Can you please send me a screenshot? It will help me understand what we
need to do here.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Faiyaz-Nylyx** [comment]
Sorry for late reply, had to figure out how to screenshot.
![olivetti-mode-standard-themes-bug](https://github.com/user-attachments/assets/fe9f6fba-7572-45ff-9dfb-a3032e180e46)
This is also so for the light theme.
![olivetti-mode-standard-theme-light-bug](https://github.com/user-attachments/assets/65ff6466-fbfa-4b05-b724-7f65225acd4d)
I used to use nano-light/dark themes, where I didn't see this happen. I don't know whether it's in the default now that I think about it... it isn't.
![oopsie](https://github.com/user-attachments/assets/ffc62ff5-0111-4894-b95c-0720aef075d1)
But can you make the margins disappear anyway? I don't know how to do that. If you could redirect me to the code I should customize I'll be grateful.
I actually thought that it wouldn't show the margins, but would be more like this:
![how-i-thought-it-should-be](https://github.com/user-attachments/assets/c67444d0-31f0-4738-b934-eede197342aa)
Thanks either way.

**Comment by Faiyaz-Nylyx** [comment]
Note how the first 3 pictures have visible margins (the first 2 are your standard-themes, the third one is default emacs I think) and the last doesn't, which I prefer (that one is an installed theme, called nano). I like everything about the new themes except for the visible margins. Nano text is too illegible for me. 
Do I close the issue since it's more of a feature request, now that I found that it's not a bug but default? First time doing this.

**Comment by protesilaos** [comment]
Here is some custom code to do this:

```elisp
;; Set up the function with all your custom faces.
(defun my-standard-faces (&rest _)
  (standard-themes-with-colors
    (set-face-attribute 'olivetti-fringe nil :background bg-main)))

(add-hook 'enable-theme-functions #'my-standard-faces)

;; Load your theme here...
```

Note that we do not want the theme to remove the background because the user option `olivetti-style` is there to mimic a page-like presentation with a more gray backdrop around the "page".

**Comment by protesilaos** [comment]
This code works with Emacs version 29 or higher.

**Comment by Faiyaz-Nylyx** [comment]
I copied and pasted your snippet into my init file, and then added a line called:
`(load-theme 'standard-dark)`
And then rebooted. However, now I get an error.
`Warning (initialization): An error occurred while loading ‘/home/faiyaz/.emacs.d/init.el’:

error: Invalid face, olivetti-fringe

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.`
So idk what to do now.

**Comment by Faiyaz-Nylyx** [comment]
I tried to change what olivetti package I was running (it was with the 2.0.7 version at melpa) but it doesn't work for the 20241030.542 version either. Installed via "package-install".

**Comment by protesilaos** [comment]
Try this variant instead. It will not fail if olivetti has not been loaded yet:

```elisp
;; Set up the function with all your custom faces.
(defun my-standard-faces (&rest _)
  (standard-themes-with-colors
   (custom-set-faces
    `(olivetti-fringe ((t :background ,bg-main))))))

(add-hook 'enable-theme-functions #'my-standard-faces)

;; Load your theme here...
```

**Comment by Faiyaz-Nylyx** [comment]
No longer errors at startup. There were two warnings that popped up the first time I actually used it, but they no longer appear. Thanks a lot! Got no screenshot, but it referenced a warning about free variables in two lines of olivetti.el code. But it works!

**Comment by protesilaos** [comment]
Those warnings are probably unrelated to this. They are produced when you install a package and usually are of immediate interest to the developer rather than the user.

**Comment by Faiyaz-Nylyx** [comment]
Then I can use it happily. Thanks a lot.
